---
title: 'Poisson Lognormal models for multivariate count data'
description: |
  In many fields of life science, count data is becoming the standard, like abundance table in ecology and micrbiology, or single-cell data in molecular biology. The Poisson lognormal model is a latent model that describes the dependency structure of the data in an underlying Gaussian layer, while the observation layer of the count is Poisson distributed. As such, it offers the flexibility of the multivariate Gaussian distribution while preserving count distributions. <br/>
  In the R package *PLNmodels*, we implement an efficient varitional strategy for inferring the standard Poisson lognormal model. We derive a series of model by transposing the classical tools from multivariate analysis, mostly tight to the Gaussian assumption of the data, to count data. *PLNmodels* includes variants for Principal Component Analysis, Discriminant Analysis, sparse covariance estimation _a.k.a._ network inference, mixture models and more coming, all designed for multivariate count data. <div class='altmetric-embed' data-badge-type='donut' data-doi="10.1007/s11222-010-9191-2"></div>
preview: https://github.com/jchiquet/PLNmodels/raw/master/inst/sticker/PLNmodels.png
author:
  - name: Julien Chiquet 
    url: http://julien.cremeriefamily.info
    affiliation: MIA Paris, INRA
    affiliation_url: https://www6.inra.fr/mia-paris
  - name: Mahendra Mariadassou
    url: https://mahendra-mariadassou.github.io/
    affiliation: MaIAGE, INRA
    affiliation_url: http://maiage.jouy.inra.fr/
  - name: Stéphane Robin
    url: https://www6.inra.fr/mia-paris/Equipes/Membres/Stephane-Robin
    affiliation: MIA Paris, INRA
    affiliation_url: https://www6.inra.fr/mia-paris
date: "`r Sys.Date()`"
journal: 
  title: "Journal of something"
  issue: x
  volume: x
  doi: ""
slug: CMR2018PLNmodels
output:
  radix::radix_article:
    toc: false
    includes: 
      in_header: altmetrics.html
bibliography: biblio_PLN.bib
creative_commons: CC BY-NC
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Introduction

blabla

### Companion data set: oak powldery mildew

blabla

## Statistical framework 

Two mains inrgedients: The Poisson lognormal distribution and the varitional approximation principle

### The Poisson log-normal model

The family of models available in the package belongs to the family of probabilistic PCA models, where the observation are not necessarily Gaussian.  In particular, we consider that observations are drawn from a Poisson lognormal distribution.

The Poisson lognormal model relates some $p$-dimensional observation vectors $\mathbf{Y}_i$ to some  $p$-dimensional vectors of Gaussian latent variables $\mathbf{Z}_i$ as follows
\begin{equation}
  \label{eq:pca-model}
  \begin{array}{rcl}
  \text{latent space } &   \mathbf{Z}_i \sim \mathcal{N}{\boldsymbol\mu},\boldsymbol\Sigma) \\
  \text{observation space } &  Y_{ij} | Z_{ij} \quad \text{indep.} & Y_{ij} | Z_{ij} \sim \mathcal{P}\left(\exp\{Z_{ij}\}\right)
  \end{array}
\end{equation}

The parameter ${\boldsymbol\mu}$ corresponds to the main effects and the latent covariance matrix $\boldsymbol\Sigma$ describes the underlying structure of dependence between the $p$ variables.

### Variational Inference 

Write this

### Illlustration of the basic PLN model

PLN with various covariance structures

Oak powldery mildew

## PLN variants

### Principal Component Analysis

### Discriminant Analysis

### Sparse network inference 

### Mixture model and clustering

## Acknowledgments {.appendix}

This is a place to recognize people and institutions. It may also be a good place
to acknowledge and cite software that makes your work possible.

## Author Contributions {.appendix}

We strongly encourage you to include an author contributions statement briefly 
describing what each author did.
