#' Poisson lognormal model with blockwise covariance
#'
#' Fit the multivariate Poisson lognormal with model with a variational algorithm. Use the (g)lm syntax for model specification (covariates, offsets, weights).
#'
#' @param formula an object of class "formula": a symbolic description of the model to be fitted.
#' @param nb_blocks vector of number of blocks for regrouping the variables/responses (dimension of the residual covariance)
#' @param data an optional data frame, list or environment (or object coercible by as.data.frame to a data frame) containing the variables in the model. If not found in data, the variables are taken from environment(formula), typically the environment from which PLN is called.
#' @param subset an optional vector specifying a subset of observations to be used in the fitting process.
#' @param weights an optional vector of observation weights to be used in the fitting process.
#' @param control a list-like structure for controlling the optimization, with default generated by [PLN_param()]. See the associated documentation
#' for details.
#'
#' @return an R6 object with class [`PLNblockfamily`], which contains
#' a collection of models with class [`PLNblockfit`]
#'
#' @rdname PLNblock
#' @include PLNblockfit-class.R
#' @examples
#' data(trichoptera)
#' trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)
#' myPLN <- PLNblock(Abundance ~ 1, nb_blocks = 1:5, data = trichoptera)
#' @seealso The classes [`PLNblockfamily`] and [`PLNblockfit`], and the and the configuration function [PLNblock_param()].
#' @importFrom stats model.frame model.matrix model.response model.offset model.weights terms
#' @export
PLNblock <- function(formula, nb_blocks = 1:5, sparsity = 0, data, subset, weights, control = PLNblock_param()) {

  ## Temporary test for deprecated use of list()
  if (!inherits(control, "PLNmodels_param"))
    stop("We now use the function PLNblock_param() to generate the list of parameters that controls the fit:
    replace 'list(my_arg = xx)' by PLNblock_param(my_arg = xx) and see the documentation of PLNblock_param().")

  ## extract the data matrices and weights
  args <- extract_model(match.call(expand.dots = FALSE), parent.frame())

  ## initialization
  if (control$trace > 0) cat("\n Initialization...")
  myPLN <- PLNblockfamily$new(nb_blocks, sparsity, args$Y, args$X, args$O, args$w, args$formula, control)

  ## optimization
  if (control$trace > 0) cat("\n Adjusting", length(myPLN$nb_blocks), "PLN with block covariance estimation with", control$backend, "optimizer\n")
  myPLN$optimize(control$config_optim)

  ## Post-treatments
  if (control$trace > 0) cat("\n Post-treatments")
  config_post <- config_post_default_PLN; config_post$trace <- control$trace
  myPLN$postTreatment(config_post)

  if (control$trace > 0) cat("\n DONE!\n")
  myPLN
}

#' Control of a PLNblock fit
#'
#' Helper to define list of parameters to control the PLN fit. All arguments have defaults.
#'
#' @param backend optimization back used, either "nlopt" or "torch". Default is "nlopt"
#' @param config_optim a list for controlling the optimizer (either "nlopt" or "torch" backend). See details
#' @param trace a integer for verbosity.
#' @param inception Set up the parameters initialization: by default, the model is initialized with a multivariate linear model applied on
#'    log-transformed data, and with the same formula as the one provided by the user. However, the user can provide a PLNfit (typically obtained from a previous fit),
#'    which sometimes speeds up the inference.
#' @return list of parameters configuring the fit.
#' @inherit PLN_param details
#' @details See [PLN_param()] for a full description of the generic optimization parameters. PLNnetwork_param() also has two additional parameters controlling the optimization due the inner-outer loop structure of the optimizer:
#' * "ftol_out" outer solver stops when an optimization step changes the objective function by less than xtol multiplied by the absolute value of the parameter. Default is 1e-6
#' * "maxit_out" outer solver stops when the number of iteration exceeds maxit_out. Default is 50
#'
#' @seealso [PLN_param()]
#' @export
PLNblock_param <- function(
    backend       = c("nlopt", "torch"),
    trace         = 1,
    config_optim  = list(init_cl=""),
    init_cl       = "ward.D2",
    inception     = NULL     # pretrained PLNfit used as initialization
) {

  if (!is.null(inception)) stopifnot(isPLNfit(inception))

  ## optimization config
  backend <- match.arg(backend)
  stopifnot(backend %in% c("torch", "nlopt"))
  if (backend == "nlopt") {
    stopifnot(config_optim$algorithm %in% available_algorithms_nlopt)
    config_opt <- config_default_nlopt
  }
  if (backend == "torch") {
    stopifnot(config_optim$algorithm %in% available_algorithms_torch)
    config_opt <- config_default_torch
  }

  config_opt$trace <- trace
  config_opt$ftol_out  <- 1e-5
  config_opt$maxit_out <- 20
  config_opt[names(config_optim)] <- config_optim

  structure(list(
    backend       = backend   ,
    trace         = trace     ,
    config_optim  = config_opt,
    init_cl       = init_cl,
    inception     = inception), class = "PLNmodels_param")
}
