#' Poisson lognormal model towards Principal Component Analysis
#'
#' Fit the PCA variants of the Poisson lognormal with a variational algorithm. Use the (g)lm syntax for model specification (covariates, offsets).
#'
#' @inheritParams PLN formula data subset weights
#' @param ranks a vector of integer containing the successive ranks (or number of axes to be considered)
#' @param control a list-like structure for controlling the optimization, with default generated by [PLNPCA_param()].  See the associated documentation.
#' for details.
#'
#' @return an R6 object with class [`PLNPCAfamily`], which contains
#' a collection of models with class [`PLNPCAfit`]
#'
#' @rdname PLNPCA
#' @examples
#' #' ## Use future to dispatch the computations on 2 workers
#' \dontrun{
#' future::plan("multisession", workers = 2)
#' }
#'
#' data(trichoptera)
#' trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)
#' myPCA <- PLNPCA(Abundance ~ 1 + offset(log(Offset)), data = trichoptera, ranks = 1:5)
#'
#' # Shut down parallel workers
#' \dontrun{
#' future::plan("sequential")
#' }
#' @seealso The classes [`PLNPCAfamily`] and [`PLNPCAfit`], and the configuration function [PLNPCA_param()].
#' @importFrom stats model.frame model.matrix model.response model.offset
#' @export
PLNPCA <- function(formula, data, subset, weights, ranks = 1:5, control = PLNPCA_param()) {

  ## Temporary test for deprecated use of list()
  if (!inherits(control, "PLNmodels_param"))
    stop("We now use the function PLNPCA_param() to generate the list of parameters that controls the fit:
    replace 'list(my_arg = xx)' by PLN_param(my_arg = xx) and see the documentation of PLNPCA_param().")

  ## extract the data matrices and weights
  args <- extract_model(match.call(expand.dots = FALSE), parent.frame())

  ## Instantiate the collection of PLN models, initialized by PLN with full rank
  if (control$trace > 0) cat("\n Initialization...")
  myPCA <- PLNPCAfamily$new(ranks, args$Y, args$X, args$O, args$w, args$formula, control)

  ## Adjust the PLN models
  if (control$trace > 0) cat("\n\n Adjusting", length(ranks), "PLN models for PCA analysis.\n")
  myPCA$optimize(control$config_optim)

  ## Post-treatments: pseudo-R2, rearrange criteria and prepare PCA visualization
  if (control$trace > 0) cat("\n Post-treatments")
  myPCA$postTreatment(control$config_post, control$config_optim)

  if (control$trace > 0) cat("\n DONE!\n")
  myPCA
}

#' Control of PLNPCA fit
#'
#' Helper to define list of parameters to control the PLNPCA fit. All arguments have defaults.
#'
#' @param backend optimization back used, either "nlopt", "torch", or "homemade". Default is "nlopt".
#'   Use "homemade" for the built-in coordinate-Newton optimizer (exact diagonal Newton steps for
#'   B, M, C, and closed-form update for S in log(S²) space), which does not depend on NLOPT.
#' @inheritParams PLN_param trace config_optim config_post inception
#' @param sequential logical. If `TRUE`, ranks are fitted in ascending order and each model is
#'    warm-started from the converged solution of the previous rank: loadings C are augmented
#'    with new columns from the inception SVD, while latent scores M and variances S are
#'    padded with zeros / 0.1 respectively. Disables parallel fitting across ranks.
#'    Default is `FALSE`.
#'
#' @return list of parameters configuring the fit.
#'
#' @inherit PLN_param details
#' @export
PLNPCA_param <- function(
    backend       = c("nlopt", "torch", "homemade"),
    trace         = 1      ,
    config_optim  = list() ,
    config_post   = list() ,
    inception     = NULL   , # pretrained PLNfit used as initialization
    sequential    = FALSE    # fit ranks sequentially, warm-starting each from the previous
) {

  if (!is.null(inception)) stopifnot(isPLNfit(inception))

  ## post-treatment config
  config_pst <- config_post_default_PLNPCA
  config_pst[names(config_post)] <- config_post
  config_pst$trace <- trace

  ## optimization config
  backend <- match.arg(backend)
  config_opt <- make_config_optim(backend, config_optim, trace,
                                  homemade_default = config_default_spectral)
  config_opt$sequential <- sequential

  structure(list(
    backend       = backend   ,
    trace         = trace     ,
    config_optim  = config_opt,
    config_post   = config_pst,
    inception     = inception   ), class = "PLNmodels_param")
}
