#' Poisson lognormal model towards Principal Component Analysis
#'
#' Fit the PCA variants of the Poisson lognormal with a variational algorithm. Use the (g)lm syntax for model specification (covariates, offsets).
#'
#' @inheritParams PLN formula data subset weights
#' @param ranks a vector of integer containing the successive ranks (or number of axes to be considered)
#' @param control a list-like structure for controlling the optimization, with default generated by [PLNPCA_param()].  See the associated documentation.
#' for details.
#'
#' @return an R6 object with class [`PLNPCAfamily`], which contains
#' a collection of models with class [`PLNPCAfit`]
#'
#' @rdname PLNPCA
#' @examples
#' #' ## Use future to dispatch the computations on 2 workers
#' \dontrun{
#' future::plan("multisession", workers = 2)
#' }
#'
#' data(trichoptera)
#' trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)
#' myPCA <- PLNPCA(Abundance ~ 1 + offset(log(Offset)), data = trichoptera, ranks = 1:5)
#'
#' # Shut down parallel workers
#' \dontrun{
#' future::plan("sequential")
#' }
#' @seealso The classes [`PLNPCAfamily`] and [`PLNPCAfit`], and the configuration function [PLNPCA_param()].
#' @importFrom stats model.frame model.matrix model.response model.offset
#' @export
PLNPCA <- function(formula, data, subset, weights, ranks = 1:5, control = PLNPCA_param()) {

  ## Temporary test for deprecated use of list()
  if (!inherits(control, "PLNmodels_param"))
    stop("We now use the function PLNPCA_param() to generate the list of parameters that controls the fit:
    replace 'list(my_arg = xx)' by PLN_param(my_arg = xx) and see the documentation of PLNPCA_param().")

  ## extract the data matrices and weights
  args <- extract_model(match.call(expand.dots = FALSE), parent.frame())

  ## Instantiate the collection of PLN models; shared SVD initialisation (LM or user inception)
  if (control$trace > 0) cat("\n Initialization...")
  myPCA <- PLNPCAfamily$new(ranks, args$Y, args$X, args$O, args$w, args$formula, control)

  ## Adjust the PLN models
  if (control$trace > 0) cat("\n\n Adjusting", length(ranks), "PLN models for PCA analysis.\n")
  myPCA$optimize(control$config_optim)

  ## Post-treatments: pseudo-R2, rearrange criteria and prepare PCA visualization
  if (control$trace > 0) cat("\n Post-treatments")
  myPCA$postTreatment(control$config_post, control$config_optim)

  if (control$trace > 0) cat("\n DONE!\n")
  myPCA
}

#' Control of PLNPCA fit
#'
#' Helper to define list of parameters to control the PLNPCA fit. All arguments have defaults.
#'
#' @param backend optimization backend, either `"nlopt"` (default, NLOPT/CCSAQ, recommended
#'   for PLNPCA: conservative per-variable steps reliably find the global basin even when
#'   the singular-value ratio d1/sqrt(n) is large), `"builtin"` (joint L-BFGS with strong
#'   Wolfe line search on all parameters simultaneously — faster per iteration but may
#'   converge to inferior local optima on ill-conditioned datasets),
#'   or `"torch"` (**experimental**: automatic differentiation via the torch package; tends to
#'   find lower loglik than `"nlopt"` and `"builtin"` on most datasets — not recommended).
#' @inheritParams PLN_param trace config_optim config_post
#' @param init_method character: strategy used to compute the starting point for the shared SVD.
#'   Either `"LM"` (default, fast: one multivariate `lm.fit` on log-transformed counts) or
#'   `"GLM"` (p independent Poisson GLMs, more accurate for complex or highly unbalanced
#'   designs). Ignored when `inception` is provided. Benchmarks show `"LM"` is as good as
#'   or better than `"GLM"` for PLNPCA in most cases; `"GLM"` is not recommended.
#'   See [compute_PLN_starting_point()].
#' @param inception an optional pre-fitted [`PLNfit`] object. When provided, its variational
#'   means `M` and regression coefficients `B` are used to compute the shared SVD
#'   `svd(M - X*B)` that initialises all ranks simultaneously. This replaces the default
#'   LM-based starting point and can improve convergence for large ranks on datasets with
#'   strong covariate effects (e.g. `inception = PLN(formula, data)`). When `NULL` (default),
#'   a fast LM is used. `init_method` is ignored when `inception` is set.
#'   **Recommendation for large rank or complex datasets**: providing a pre-fitted PLN can
#'   substantially improve the ELBO, especially for high ranks (e.g. rank > `sqrt(p)`) where
#'   the LM initialisation may miss a better basin. Benchmark shows gains of up to +87 loglik
#'   on oaks (p=114, rank=20) vs the default LM init.
#' @param sequential logical. If `TRUE`, ranks are fitted in ascending order and each model is
#'    warm-started from the converged solution of the previous rank: loadings C are augmented
#'    with new columns from the inception SVD, while latent scores M and variances S2 are
#'    padded with zeros / 0.01 respectively. Disables parallel fitting across ranks.
#'    Default is `FALSE`.
#'
#' @return list of parameters configuring the fit.
#'
#' @inherit PLN_param details
#' @export
PLNPCA_param <- function(
    backend       = c("nlopt", "builtin", "torch"),
    trace         = 1      ,
    config_optim  = list() ,
    config_post   = list() ,
    inception     = NULL   , # pretrained PLNfit used as initialization
    init_method   = c("LM", "GLM"),
    sequential    = FALSE    # fit ranks sequentially, warm-starting each from the previous
) {

  if (!is.null(inception)) stopifnot(isPLNfit(inception))
  init_method <- match.arg(init_method)

  ## post-treatment config
  config_pst <- config_post_default_PLNPCA
  config_pst[names(config_post)] <- config_post
  config_pst$trace <- trace

  ## optimization config
  backend <- match.arg(backend)
  if (backend == "torch")
    message("torch backend is experimental: may converge to suboptimal solutions or fail on some datasets.")
  config_opt <- make_config_optim(backend, config_optim, trace,
                                  builtin_default = config_default_plnpca)
  config_opt$sequential <- sequential

  structure(list(
    backend       = backend     ,
    trace         = trace       ,
    config_optim  = config_opt  ,
    config_post   = config_pst  ,
    inception     = inception   ,
    init_method   = init_method   ), class = "PLNmodels_param")
}
