# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimization_VEstep_PLN <- function(par, Y, X, O, Theta, Sigma, options) {
    .Call('_PLNmodels_optimization_VEstep_PLN', PACKAGE = 'PLNmodels', par, Y, X, O, Theta, Sigma, options)
}

optimization_PLN <- function(par, Y, X, O, w, options) {
    .Call('_PLNmodels_optimization_PLN', PACKAGE = 'PLNmodels', par, Y, X, O, w, options)
}

