# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_test_nlopt <- function() {
    .Call('_PLNmodels_cpp_test_nlopt', PACKAGE = 'PLNmodels')
}

nlopt_optimize_diagonal <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_diagonal', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_diagonal <- function(data, params, B, Omega, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_diagonal', PACKAGE = 'PLNmodels', data, params, B, Omega, config)
}

nlopt_optimize_fixed <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_fixed', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep <- function(data, params, B, Omega, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep', PACKAGE = 'PLNmodels', data, params, B, Omega, config)
}

nlopt_optimize_genetic_modeling <- function(init_parameters, Y, X, O, w, C, configuration) {
    .Call('_PLNmodels_nlopt_optimize_genetic_modeling', PACKAGE = 'PLNmodels', init_parameters, Y, X, O, w, C, configuration)
}

nlopt_optimize_rank <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_rank', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_rank <- function(data, params, B, C, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_rank', PACKAGE = 'PLNmodels', data, params, B, C, config)
}

nlopt_optimize_spherical <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_spherical', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_spherical <- function(data, params, B, Omega, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_spherical', PACKAGE = 'PLNmodels', data, params, B, Omega, config)
}

zipln_vloglik <- function(Y, X, O, Pi, Omega, B, R, M, S) {
    .Call('_PLNmodels_zipln_vloglik', PACKAGE = 'PLNmodels', Y, X, O, Pi, Omega, B, R, M, S)
}

optim_zipln_Omega_full <- function(M, X, B, S) {
    .Call('_PLNmodels_optim_zipln_Omega_full', PACKAGE = 'PLNmodels', M, X, B, S)
}

optim_zipln_Omega_spherical <- function(M, X, B, S) {
    .Call('_PLNmodels_optim_zipln_Omega_spherical', PACKAGE = 'PLNmodels', M, X, B, S)
}

optim_zipln_Omega_diagonal <- function(M, X, B, S) {
    .Call('_PLNmodels_optim_zipln_Omega_diagonal', PACKAGE = 'PLNmodels', M, X, B, S)
}

optim_zipln_B_dense <- function(M, X) {
    .Call('_PLNmodels_optim_zipln_B_dense', PACKAGE = 'PLNmodels', M, X)
}

optim_zipln_zipar_covar <- function(R, init_B0, X0, configuration) {
    .Call('_PLNmodels_optim_zipln_zipar_covar', PACKAGE = 'PLNmodels', R, init_B0, X0, configuration)
}

optim_zipln_R_var <- function(Y, X, O, M, S, Pi, B) {
    .Call('_PLNmodels_optim_zipln_R_var', PACKAGE = 'PLNmodels', Y, X, O, M, S, Pi, B)
}

optim_zipln_R_exact <- function(Y, X, O, M, S, Pi, B) {
    .Call('_PLNmodels_optim_zipln_R_exact', PACKAGE = 'PLNmodels', Y, X, O, M, S, Pi, B)
}

optim_zipln_M <- function(init_M, Y, X, O, R, S, B, Omega, configuration) {
    .Call('_PLNmodels_optim_zipln_M', PACKAGE = 'PLNmodels', init_M, Y, X, O, R, S, B, Omega, configuration)
}

optim_zipln_S <- function(init_S, O, M, R, B, diag_Omega, configuration) {
    .Call('_PLNmodels_optim_zipln_S', PACKAGE = 'PLNmodels', init_S, O, M, R, B, diag_Omega, configuration)
}

cpp_test_packing <- function() {
    .Call('_PLNmodels_cpp_test_packing', PACKAGE = 'PLNmodels')
}

