# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
optimization_PLN <- function(par, Y, X, O, options) {
    .Call('_PLNmodels_optimization_PLN', PACKAGE = 'PLNmodels', par, Y, X, O, options)
}

#' @export
optimization_PLNnetwork <- function(par, Y, X, O, Omega, log_det_Omega, options) {
    .Call('_PLNmodels_optimization_PLNnetwork', PACKAGE = 'PLNmodels', par, Y, X, O, Omega, log_det_Omega, options)
}

#' @export
optimization_PLNPCA <- function(par, Y, X, O, rank, options) {
    .Call('_PLNmodels_optimization_PLNPCA', PACKAGE = 'PLNmodels', par, Y, X, O, rank, options)
}

#' @export
fn_optim_PLN_Cpp <- function(par, Y, X, O, KY) {
    .Call('_PLNmodels_fn_optim_PLN_Cpp', PACKAGE = 'PLNmodels', par, Y, X, O, KY)
}

#' @export
fn_optim_PLNnetwork_Cpp <- function(par, log_detOmega, Omega, Y, X, O, KY) {
    .Call('_PLNmodels_fn_optim_PLNnetwork_Cpp', PACKAGE = 'PLNmodels', par, log_detOmega, Omega, Y, X, O, KY)
}

#' @export
fn_optim_PLNPCA_Cpp <- function(par, q, Y, X, O, KY) {
    .Call('_PLNmodels_fn_optim_PLNPCA_Cpp', PACKAGE = 'PLNmodels', par, q, Y, X, O, KY)
}

